FOLDER_IN : /home/test/GB_tests/test_in
FOLDER_OUT : /home/test/GB_tests/test_out
FOLDER_EXTRACT : /home/test/GB_tests/extract
COUNT : 5
ARC_NAME : arch2
FILE_SIZE : 1M
ARC_TYPE: "zip"  # Тип архива, например, "7z", "zip", "tar", и т.д.
host : 192.168.0.3
user: test
password: test
port: 22
remote_path: /home/test/p7zip-full.deb
local_path:
pkgname: p7zip-full